### ISSUE TITLE
(login) After registertion you get login screen without header&footer

### ISSUE THREAD

**Issue by ScreamQueen** [Pinhead877/SocialTrivia#49]
אחרי שנרשמתי לאתר אני מקבלת דף כניסה לבן בלי העיצוב של האתר (רק עם אפשרות להכניס שם משתמש וסיסמא).

**Comment by Pinhead877** [comment]
בעיה להציג את התחברות פעמיים אז לא הצגתי את העיצוב של האתר
הוספתי את הלוגו בצד בשביל העיצוב

**Comment by Pinhead877** [comment]
לא משנה סידרתי את זה

**Comment by ScreamQueen** [comment]
סבבה לגמרי

בתאריך 30 באוג׳ 2016 18:35,‏ "Alex Apchiory" notifications@github.com כתב:
