### ISSUE TITLE
(create) This qust didn't accepted :\

### ISSUE THREAD

**Issue by ScreamQueen** [Pinhead877/SocialTrivia#51]
ניסיתי להכניס את השאלה הנ" ל בתור שאלה חדשה - וקיבלתי את ההודעה שתשובה לא יכולה להכיל יותר מ7 תווים. אבל אין לי 7 תווים במילה אחת של התשובה...

והנה השאלה
Which star appears on the flag of Israel?
והתשובה שניסיתי להכניס:
Star of David

**Comment by Pinhead877** [comment]
אם אני לא תועה 
"משחק מילים"
של עד שתי מילים בתשובה
צריך לבדוק ולהוסיף הודעה מתאימה

**Comment by ScreamQueen** [comment]
הכנסתי שאלה שהתשובה עליה היא let it be וזה אישר....

בתאריך 30 באוג׳ 2016 18:12,‏ "Alex Apchiory" notifications@github.com כתב:

**Comment by Pinhead877** [comment]
כנראה יש לו בעיה עם יהודים
לא רוצה מגן דויד

**Comment by Pinhead877** [comment]
זה הוסיף לי את התשובה

**Comment by Pinhead877** [comment]
את זוכרת את השאלה שניסית לכתוב?

**Comment by ScreamQueen** [comment]
כתבתי לך אותה בתוך המשימה שפתחתי!!

בתאריך 30 באוג׳ 2016 21:09,‏ "Alex Apchiory" notifications@github.com כתב:

**Comment by Pinhead877** [comment]
הוספתי את השאלה עם התשובה לא הייתה בעיה

**Comment by ScreamQueen** [comment]
חחחחח..
זה בטוח פונקציה שעשית.... ;) ;) ;)

בתאריך 30 באוג׳ 2016 22:56,‏ "Alex Apchiory" notifications@github.com כתב:
