### ISSUE TITLE
In the game: After I finish the game,  the playes can to continue the play

### ISSUE THREAD

**Issue by ScreamQueen** [Pinhead877/SocialTrivia#52]
סיימנו לשחק את המשחק, לחצתי במסך הראשי "סיים משחק" הצגתי את התוצאות... אבל הצגים של השחקנים עדיין מאפשרים לבחור שאלה, לענות עליה ולקבל עליה נקודות... 
במקום שהמערכת תזרוק אותם החוצה.

**Comment by Pinhead877** [comment]
זה רק ממשיך להראות את המסך אבל יש שגיאה כאשר מנסים לגשת לשאלה
